# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Lovely Photos')),
                ('sound', models.FileField(blank=True, null=True, upload_to='sounds', verbose_name='Lovely Sounds')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Lovely Words')),
            ],
        ),
    ]
