# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\Ian\\Documents\\ImportantDocs\\FirstAnniversary\\iloveyou\\media//pictures', verbose_name='Lovely Photos'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Ian\\Documents\\ImportantDocs\\FirstAnniversary\\iloveyou\\media//sounds', verbose_name='Lovely Sounds'),
        ),
    ]
