# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20170624_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='picture_rotation',
            field=models.IntegerField(blank=True, choices=[(0, '0 Degrees'), (90, '90 Degrees'), (180, '180 Degrees'), (270, '270 Degrees')], default=0, null=True, verbose_name='Lovely Rotation Angle'),
        ),
    ]
