# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_memory_picture_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Lovely Object Name'),
        ),
    ]
