# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'Memories'},
        ),
    ]
