# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_auto_20170625_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='shown',
            field=models.BooleanField(default=False, verbose_name='Lovely Shown'),
        ),
    ]
